# Generated by Django 2.0 on 2017-12-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('cell_phone', models.CharField(max_length=10)),
                ('office_phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('about_me', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('facebook_profile_link', models.URLField()),
                ('twitter_profile_link', models.URLField()),
                ('linkedin_profile_link', models.URLField()),
                ('github_profile_link', models.URLField()),
                ('google_plus_profile_link', models.URLField()),
                ('stackoverflow_profile_link', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('built_with', models.ManyToManyField(to='website.ProgrammingLanguage')),
            ],
        ),
    ]
